name: ECS CDK Build

on:
  push:
    paths:
      - '/cdk/**'
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

env:
  OCTOPUS_SPACE: 'Default'
  OCTOPUS_PROJECT_NAME: 'AWS CDK Deployment' 
  PACKAGE_ID: 'ecs-cdk'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: echo "PACKAGE_VERSION=$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_ENV

      - name: Compress CDK directory
        run: zip -r ${{ env.PACKAGE_ID }}.${{ env.PACKAGE_VERSION }}.zip cdk

      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1
        with: 
          server: https://creid.octopus.app
          service_account_id: d7b6439c-edd8-4f5c-b035-ad3a647807b4
      
      - name: Push package to Octopus
        uses: OctopusDeploy/push-package-action@v4
        env:
          OCTOPUS_SPACE: ${{ env.OCTOPUS_SPACE }}
        with:
          packages: ${{ env.PACKAGE_ID }}.${{ env.PACKAGE_VERSION }}.zip
          overwrite_mode: OverwriteExisting

      - name: Push build information to Octopus
        uses: OctopusDeploy/push-build-information-action@v4
        env:
          OCTOPUS_SPACE: ${{ env.OCTOPUS_SPACE }}
        with:
          packages: ${{ env.PACKAGE_ID }}
          version: ${{ env.PACKAGE_VERSION }}
          overwrite_mode: OverwriteExisting

      - name: Create Octopus release
        uses: OctopusDeploy/create-release-action@v4
        env:
          OCTOPUS_SPACE: ${{ env.OCTOPUS_SPACE }}
        with:
          project: ${{ env.OCTOPUS_PROJECT_NAME }}
          packages: ${{ env.PACKAGE_ID }}.${{ env.PACKAGE_VERSION }}
